In [ ]:
1. What does Pandas stand for?
Ans: Pandas stand for panel data and/or Pythom Data Analysis.

2. What are the 2 collections used in Pandas?
Ans: Series and dataframes.

3. Name 4 things Pandas can do for us.
Ans: Data cleaning, data visualization, data normalization, and data inspection.

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?.
Ans: 

5. What is a CSV?
Ans: A comma seperated value.

6. When cleaning data what values do we not like in our data?
Ans: Null and empty values.

In [5]:
#Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np 
array = np.arange(12)
reshaped_array = array.reshape((2, 3, 2))
print (reshaped_array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [28]:
#8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
import numpy as np 
array = np.linspace(0, 10, 3) 
print (array)

[ 0.  5. 10.]


In [29]:
#9. Make a Deep Copy of the above array
import copy
original_array = [0, 5, 10]
deep_copied_array = copy.deepcopy(original_array)
print(deep_copied_array)

[0, 5, 10]


In [74]:
#0. Concatenate these 3 arrays into a new array named 'newArray'...
   # ```python
#([[25, 16]])
#([[11, 2], [13, 4]])
#([[7, 81], [5, 6], [11, 12]])

import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newarray = np.concatenate((array1, array2, array3), axis=0)

print(newarray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [36]:
import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newarray = np.concatenate((array1, array2, array3), axis=0)

print(newarray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [38]:
#11. Sort 'newArray' in order into 'sortedArray'
import numpy as np
newarray = np.concatenate((array1, array2, array3), axis=0)
sortedarraymatrix = np.sort(newarray, axis=0).reshape(newarray.shape)
print("Sorted Matrix Array:")
print(sortedarraymatrix)

Sorted Matrix Array:
[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


In [77]:
#12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

import numpy as np 
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

print(array1, array2, array3)

[[25 16]] [[11  2]
 [13  4]] [[ 7 81]
 [ 5  6]
 [11 12]]


In [ ]:
13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
import numpy as np 
one = np.array([1, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])

comboarray = np.concatenate((one, two, three))
sortedcomboarray = np.sort(comboarray)

print(sortedcomboarray)

[ 0  1  1  2  3  4  5  6  7 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [ ]:
14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [44]:
import numpy as np 
comboarray = np.concatenate((one, two, three))
sortedcomboarray = np.sort(comboarray)

sec1 = sortedcomboarray[1]
sec2 = sortedcomboarray[2:]
sec3 = sortedcomboarray[3:14]
sec4 = sortedcomboarray[-6]
sec5 = sortedcomboarray[:16]
sec6 = sortedcomboarray[20::2]
sec7 = sortedcomboarray[::-5]

print("sec1:", sec1)
print("sec2:", sec2)
print("sec3:", sec3)
print("sec4:", sec4)
print("sec5:", sec5)
print("sec6:", sec6)
print("sec7:", sec7)


sec1: 1
sec2: [ 1  2  3  4  5  6  7 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 2  3  4  5  6  7 11 12 13 14 15]
sec4: 22
sec5: [ 0  1  1  2  3  4  5  6  7 11 12 13 14 15 16 17]
sec6: [24 26]
sec7: [27 22 15  7  2]


In [ ]:
15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object


In [50]:
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name='Ingredients')
quantity = pd.Series([4, 1, 2, 1], name='Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name='Unit')
df = pd.DataFrame({
    'ingredients': ingredients,
    'quantity': quantity, 
    'unit': unit   
})

print(df)

  ingredients  quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [ ]:
, 16. Take this data and create a DataFrame named studentData], 
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [60]:
import pandas as pd

studentinfo = {
    'name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'], 
    'height': [5.1, 6.2, 51, 5.2], 
    'qualification': ["Msc", 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dhaka'],
    'age': [21, 23, 24, 21], 
    'pets': ['dog', 'bunny', 'chinchilla', 'parrot'], 
    'sport': ['darts', 'basketball', 'paddleboarding', 'cricket']
    
}
studentinfo = pd.DataFrame
print(studentinfo)

<class 'pandas.core.frame.DataFrame'>


In [61]:
import pandas as pd

data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dhaka'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)

print(studentData)


      Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc    Dhaka   21      Parrot         Cricket


In [ ]:
17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [65]:
import pandas as pd

data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dhaka'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    
}

studentData = pd.DataFrame(data)
Desserts = ['icecream', "cashew fudge", "waffels", "carrot halwa"]

studentData['Desserts'] = Desserts
print(studentData)

      Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc    Dhaka   21      Parrot         Cricket   

       Desserts  
0      icecream  
1  cashew fudge  
2       waffels  
3  carrot halwa  


In [ ]:
18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [70]:
import pandas as pd

data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dhaka'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    
}
studentData = pd.DataFrame(data)
sorted_studentData = studentData.sort_values(by=['Name', 'Address'])
print(sorted_studentData)

      Name  Height Qualification  Address  Age        Pets           Sport
3     Anuj     5.2           Msc    Dhaka   21      Parrot         Cricket
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball


In [ ]:
19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [73]:
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')
print("DataFrame saved to 'cows_and_goats.csv'.")


DataFrame saved to 'cows_and_goats.csv'.


In [83]:
#20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd 

veggie_data = pd.DataFrame({
    'veggie' : ['Tomato', 'Green Beans', 'Onion'],
    'quantity' : [1, 2, 3]
})
veggie_data.to_csv('veggiedata.csv')